openapi: 3.0.0
info:
  title: API des Examens
  version: 1.0.0
paths:
  /exams:
    get:
      summary: Récupérer la liste des examens
      responses:
        '200':
          description: Liste des examens récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exam'
    post:
      summary: Créer un nouvel examen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exam'
      responses:
        '201':
          description: Examen créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exam'

components:
  schemas:
    Exam:
      type: object
      properties:
        student:
          type: object
          properties:
            first_name:
              type: string
            last_name:
              type: string
          required:
            - first_name
            - last_name
        meeting_point:
          type: string
        date:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - A organiser
            - Annulé
            - Recherche de place
            - Confirmé
      required:
        - student
